[profile.default]
src = "src"
out = "out"
solc_version = "0.8.21"
libs = ["node_modules", "lib"]
remappings = [
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
